In [1]:
%load_ext autoreload
%autoreload 2
import sys
sys.path.append('../')

In [2]:
import numpy as np

In [42]:
t1 = np.array([1,2,3,4,5,6,7,8])
t1 = t1.reshape([2,2,2])

In [45]:
t1.squeeze()[0,0,0] = 42
t1.shape

(2, 2, 2)

In [23]:
coords = np.stack(np.meshgrid(np.arange(10), np.arange(10), indexing='ij'))

In [21]:
mask = np.zeros((10,10), dtype=bool)
mask[(0,1,3), (2,3,4)] = True

In [24]:
t = coords[:, mask]

In [29]:
if np.ones(3,dtype=bool) & np.ones(3, dtype=bool):
    print('A')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [9]:
from pathlib import Path
import shutil

In [2]:
import tiledb, numpy as np, tempfile

In [10]:
db_path = "./test_tdb"
shutil.rmtree(db_path)

In [11]:
dim1 = tiledb.Dim(domain=(0,1000000), tile=100, dtype=np.uint64)
dim2 = tiledb.Dim(domain=(0,1000000), tile=100, dtype=np.uint64)
dom = tiledb.Domain(dim1, dim2)

In [70]:
t = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16], dtype=np.int32)

In [88]:
img = t.reshape((4,4))
img

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [94]:
img[::2,:].shape

(2, 4)

In [96]:
np.stack([img[::2,::2], img[1::2,::2], img[::2,1::2], img[1::2,1::2]], axis=2).mean(axis=2)

array([[ 3.5,  5.5],
       [11.5, 13.5]])

In [91]:
f = np.ones(10)
np.ceil(f)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [69]:
t.view(np.dtype('i4,i4,i4')) + t2.view(np.dtype('i4,i4,i4'))

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype([('f0', '<i4'), ('f1', '<i4'), ('f2', '<i4')]), dtype([('f0', '<i4'), ('f1', '<i4'), ('f2', '<i4')])) -> dtype([('f0', '<i4'), ('f1', '<i4'), ('f2', '<i4')])

In [65]:
schema = tiledb.ArraySchema(domain=dom, attrs=[(tiledb.Attr(name="a1", dtype=np.int64)),])

In [13]:
ar = tiledb.DenseArray.create(db_path, schema)

In [15]:
type(ar)

NoneType

In [50]:
for i in range(1):
    with tiledb.DenseArray(db_path, mode='r') as A0:
        with tiledb.DenseArray(db_path, mode='w') as A:
            t = np.ones((10,10))
            t[0:10, 5] = 5
            A[100000:100010, 100000:100010] = {"a1": t}
        print(A0[100000:100010, 100000:100010]["a1"])
        #A[1,1] = {'a1', np.ones((1,), dtype=np.int64)}

[[1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]
 [1 1 1 1 1 4 1 1 1 1]]


In [51]:

with tiledb.DenseArray(db_path, mode='r') as A:
        for i in range(100):
                tmp = A[100000:100010, 100000:100010]["a1"]
tmp[0:10, 5]

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])